using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel;

namespace Utility
{
    public class EnumModel
    {
        public enum QR_SCENE
        {
            [Description("临时二维码")]
            QR_SCENE,
            [Description("永久二维码")]
            QR_LIMIT_SCENE,
            [Description("永久的字符串")]
            QR_LIMIT_STR_SCENE,
        }
        public enum WechatServiceType
        {
            [Description("报事报修")]
            bsbx,
            [Description("建议反馈")]
            yjfk,
            [Description("投诉举报")]
            tsjb,
        }
        public enum PriceRangeType
        {
            [Description("按次")]
            bcyl,
            [Description("按年")]
            qnyl,
        }
        public enum DeviceSettingCode
        {
            [Description("巡检任务生成时间设置")]
            checktimesetup,
            [Description("维保任务生成时间设置")]
            repairtimesetup,
        }
        public enum RepairStatus
        {
            [Description("待分派")]
            daifenpei,
            [Description("待处理")]
            daichuli,
            [Description("已完成")]
            yiwancheng,
            [Description("已归档")]
            yiguidang,
        }
        public enum ContractStatus
        {
            [Description("合同预定")]
            yuding,
            [Description("正常履行")]
            tongguo,
            [Description("合同终止")]
            zhongzhi,
            [Description("合同作废")]
            deleted,
        }
        public enum ZhuangXiuStatus
        {
            [Description("申请中")]
            shenqing,
            [Description("审批通过")]
            shenpiyes,
            [Description("审批拒绝")]
            shenpino,
            [Description("装修中")]
            zhuangxiu,
            [Description("已验收")]
            yanshou,
        }
        public enum WechatMsgType
        {
            [Description("通知")]
            tongzhi,
            [Description("活动")]
            huodong,
            [Description("新闻")]
            news,
        }
        public enum WechatContactType
        {
            [Description("服务中心电话")]
            fuwu,
            [Description("便民电话")]
            bianmin,
            [Description("400全国统一电话")]
            tongyi,
            [Description("呼叫物业")]
            hujiaowuye,
        }
        public enum ChargeSummaryCalculateAreaType
        {
            [Description("计费面积")]
            jifei,
            [Description("建筑面积")]
            jianzhu,
            [Description("套内面积")]
            taonei,
            [Description("公摊面积")]
            gongtan,
            [Description("产权面积")]
            chanquan,
            [Description("使用面积")]
            shiyong,
            [Description("配套面积")]
            peitao
        }
        public enum CKCategoryType
        {
            [Description("公司名称")]
            company,
            [Description("仓库名称")]
            warehouse,
            [Description("物品类别")]
            category,
            [Description("商品")]
            product,
            [Description("部门")]
            department
        }
        public enum ChargeDiscountType
        {
            [Description("按折扣")]
            percent,
            [Description("固定金额")]
            fixedamount,
            [Description("临时输入")]
            writeamount
        }
        public enum ChargeSummaryWeiYueDayMonth
        {
            [Description("按天")]
            day,
            [Description("按月")]
            month,
        }
        public enum ChargeSummaryWeiYueBeforeAfter
        {
            [Description("提前")]
            before,
            [Description("延后")]
            after,
        }
        public enum ChargeSummaryWeiYueStartDate
        {
            [Description("计费开始日期")]
            starttime,
            [Description("计算结束日期")]
            endtime,
        }
        public enum BalanceStatus
        {
            [Description("未结算")]
            balanceno,
            [Description("已结算")]
            balanceyes,
            [Description("已销单")]
            complete,
        }
        public enum InCategoryTypeDefine
        {
            [Description("入库")]
            ruku,
            [Description("出库")]
            chuku,
        }
        public enum PrintTypeDefine
        {
            [Description("A4三等分")]
            A4Three,
            [Description("A4二等分")]
            A4Two,
        }
        public enum DefineFieldTableName
        {
            [Description("资源信息")]
            RoomBasic,
            [Description("业主/租户")]
            RoomPhoneRelation,
        }
        public enum OperationModule
        {
            [Description("授权模块")]
            CompanyModule,
            [Description("用户角色权限")]
            RoleModule,
            [Description("用户项目权限")]
            RoleProject,
            [Description("用户登录")]
            UserLogin,
            [Description("用户退出")]
            UserLogout,
            [Description("用户新增")]
            AddUser,
            [Description("资源新增")]
            ProjectDelete,
            [Description("用户删除")]
            RemoveUser,
            [Description("用户权限修改")]
            RoleModuleSave,
            [Description("房间住户信息删除")]
            RoomPhoneRelationDelete,
            [Description("工单新增")]
            ServiceAdd,
            [Description("工单修改")]
            ServiceEdit,
            [Description("工单删除")]
            ServiceDel,
            [Description("工单派单")]
            ServicePaiDan,
            [Description("工单处理")]
            ServiceProcess,
            [Description("工单办结")]
            ServiceBanJie,
            [Description("工单回访")]
            ServiceCallBack,
            [Description("工单关单")]
            ServiceClose,
            [Description("工单销单")]
            ServiceXiaoDan,
            [Description("工单类型修改")]
            ServiceTypeEdit,
            [Description("工单类型删除")]
            ServiceTypeDel,
            [Description("工单审计")]
            ServiceShenJi,
            [Description("工单重新开单")]
            ServiceReOpen,
            [Description("工单重大投诉")]
            ServiceMoreImportant,
            [Description("工单暂不回访")]
            ServiceCanNotCallBack,
        }
        public enum AnalysisChargeFieldPageCode
        {
            [Description("收费汇总")]
            ShouFeiLvSummaryAnalysis,
            [Description("月度报表")]
            MonthFeeAnalysis,
            [Description("实收明细表")]
            RealCostMingXinAnalysis,
        }
        public enum ZhuangXiuFileType
        {
            [Description("装修申请")]
            addzhuangxiu,
            [Description("装修巡检")]
            addxunjian,
            [Description("装修验收")]
            addyanshou,
        }
        public enum DeviceCycleType
        {
            [Description("按天")]
            day,
            [Description("按月")]
            month,
        }
        public enum WechatServiceFromDefine
        {
            [Description("微信平台")]
            weixin,
            [Description("APP内部报事")]
            app,
            [Description("物业前台")]
            system,
            [Description("营销前台")]
            businessfront,
            [Description("400电话")]
            four00call,
            [Description("其他")]
            other,
        }
        public enum DeviceTaskFromDefine
        {
            [Description("系统生成")]
            system,
            [Description("客服中心")]
            customerservice,
            [Description("内部报事")]
            internalpost,
        }
        public enum DeviceTaskTypeDefine
        {
            [Description("定期维保")]
            system_repair,
            [Description("定期巡检")]
            system_check,
            [Description("临时维保")]
            manual_repair,
            [Description("临时巡检")]
            manual_check,
            [Description("日常维修")]
            normal_task,
        }
        public enum LotteryTypeDefine
        {
            [Description("转盘")]
            Turntable,
            [Description("砸金蛋")]
            Goldenegg,
            [Description("刮一刮")]
            Shave,
            [Description("摇一摇")]
            Shake,
        }
        public enum LotteryRepeatDefine
        {
            [Description("每天")]
            Everyday,
            [Description("每周")]
            Everyweek,
            [Description("每月")]
            Everymonth,
            [Description("活动期间")]
            Wholeactive,
        }
        public enum LotteryConsumeTypeDefine
        {
            [Description("普通抽奖")]
            NormalPrize,
            [Description("积分抽奖")]
            PointPrice,
        }
        public enum LotteryPrizeTypeDefine
        {
            [Description("实物奖品")]
            PhysicalGoods,
            [Description("微信红包")]
            CashRed,
        }
        public enum WechatRentHomeTypeDefine
        {
            [Description("整租")]
            zhengzu,
            [Description("合租")]
            hezu,
            [Description("主卧")]
            zhuwo,
            [Description("次卧")]
            ciwo,
        }
        public enum WechatRentRequestRentTypeDefine
        {
            [Description("出租")]
            chuzu,
            [Description("出售")]
            chushou,
            [Description("求租")]
            qiuzhu,
            [Description("求购")]
            qiugou,
        }
        public enum WechatRentRequestBuildingPropertyDefine
        {
            [Description("高层")]
            gaoceng,
            [Description("洋房")]
            yangfang,
            [Description("别墅")]
            bieshu,
            [Description("车位")]
            chewei,
            [Description("商铺")]
            shangpu,
            [Description("公寓")]
            gongyu,
            [Description("写字楼")]
            xiezilou,
            [Description("其他")]
            qita,
        }
        public enum PaymentTypeDefine
        {
            [Description("微信支付")]
            wx,
            [Description("支付宝支付")]
            alipay,
            [Description("汇收银")]
            huishouyin,
            [Description("APP微信支付")]
            app_wx,
            [Description("APP支付宝支付")]
            app_alipay,
            [Description("用户账户微信充值")]
            app_chongzhi_wx,
            [Description("用户账户支付宝充值")]
            app_chongzhi_alipay,
            [Description("APP账户余额支付")]
            app_balance_pay,
        }
        public enum ContractDivideTypeDefine
        {
            [Description("固定比例")]
            fixedpercent,
            [Description("阶梯比例")]
            jietipercent,
        }
        public enum SysMenuGroupNameDefine
        {
            [Description("物业内控")]
            wynk,
            [Description("交易管理")]
            jygl,
            [Description("结算平台")]
            jspt,
            [Description("数据中心")]
            sjzx,
            [Description("系统设置")]
            xtsz,
            [Description("业主APP管理")]
            appgl,
            [Description("内控APP管理")]
            wynkapp,
        }
        public enum ProjectTreeTypeDefine
        {
            [Description("公司")]
            company,
            [Description("资源")]
            project,
            [Description("公共资源")]
            publicproject,
            [Description("组织")]
            orgnization,
        }
        public enum Mall_CategoryTypeDefine
        {
            [Description("商品分类")]
            productcategory,
            [Description("商户类别")]
            businesscategory,
            [Description("发帖类别")]
            threadcategory,
        }
        public enum Mall_OrderPaymentMethodDefine
        {
            [Description("微信支付")]
            wxpay,
            [Description("支付宝支付")]
            alipay,
            [Description("后台支付")]
            platform,
            [Description("账户余额支付")]
            balance,
            [Description("积分余额支付")]
            point,
            [Description("免费")]
            free,
            [Description("微信+积分支付")]
            wxpay_point,
            [Description("支付宝+积分支付")]
            alipay_point,
            [Description("账户余额+积分支付")]
            balance_point,
            [Description("岗位积分支付")]
            staffpoint,
        }
        public enum MallContentNameDefine
        {
            [Description("关于我们")]
            aboutus,
            [Description("客户热线")]
            contactus,
            [Description("分享标题")]
            sharetitle,
            [Description("分享描述")]
            sharedescription,
            [Description("分享Android下载地址")]
            androiddownloadurl,
            [Description("分享IOS下载地址")]
            iosdownloadurl,
        }
        public enum Mall_ThridLoginDefine
        {
            [Description("微信登录")]
            wxlogin,
            [Description("微博登录")]
            weibologin,
            [Description("qq登录")]
            qqlogin,
        }
        public enum SocketNotifyDefine
        {
            [Description("微信在线客服通知")]
            notifychat,
            [Description("清除缓存通知")]
            notifyclearcache,
            [Description("报事报修通知")]
            notifyservice,
            [Description("订单付款完成通知")]
            notifyorderpaied,
            [Description("订单退款申请通知")]
            notifyorderrefundrequest,
            [Description("投诉建议通知")]
            notifysuggestion,
        }
        public enum PublicProjectTypeDefine
        {
            [Description("公司名称")]
            company,
            [Description("小区名称")]
            xiaoqu,
            [Description("公共资源")]
            publicproject,
        }
        public enum ContractModifyLogDefine
        {
            [Description("合同信息变更")]
            htbg,
            [Description("收费标准变更")]
            htsfbzbg,
            [Description("收费标准修改")]
            htsfbzxz,
            [Description("收费标准续")]
            htsfbzxuzu,
            [Description("收费标准删除")]
            htsfbzsc,
            [Description("租赁资源新增")]
            htzlzyxz,
            [Description("租赁资源删除")]
            htzlzysc,
            [Description("新增收款方")]
            contractcustomerpartaadd,
            [Description("删除收款方")]
            contractcustomerpartaremove,
            [Description("新增承租方")]
            contractcustomerpartbadd,
            [Description("删除承租方")]
            contractcustomerpartbremove,
        }
    }
}
